version: '3.2'
name: emiservcedent
services:
  wildfly:
    build:
      context: ${DOCKER_PROJECT_PATH}/builds/wildfly-dist
      args:
        - KEYCLOAK_URI_ARG=${KEYCLOAK_URI_ARG}
    container_name: wildfly-${APP_PROJECT_NAME}
    hostname: wildfly-${APP_PROJECT_DOCKER_SERVER_NAME}
    environment:
     - ADMIN_USER=$WILDFLY_ADMIN_USER
     - ADMIN_PASSWORD=$WILDFLY_ADMIN_PASS
    ports:
     - ${WILDFLY_PORT}:8080
     - ${WILDFLY_ADMIN_PORT}:9990
    volumes:
     - ${WILDFLY_DEPLOY_DIR}:/opt/jboss/wildfly/standalone/deployments
     - ${WILDFLY_CONFIG_DIR}:/opt/jboss/webapps/config
     - ${APP_FILES_BASE_FOLDER}/assets:/app/${APP_PROJECT_NAME}/assets
     - ${APP_FILES_BASE_FOLDER}/var:/app/${APP_PROJECT_NAME}/var
    